### PR TITLE
Traffic Cop, terrier engine instead of Sqlite

### PR DESCRIPTION
**Pull request by lmwnshn**
Basically just glue code that can send incoming SQL queries all the way to the binder.

```
Network -> Parser -> Binder ->  ??? (optimizer) -> TPL
                       ^ we are here!
```

---

Status:

- [x] Create works!
- [ ] I'm apparently not awake enough to fix a memory leak. Will ask Matt for help later.
- [ ] Once the leak is resolved, I'll uncomment four lines in the postgres network commands. If things go well, then it binds and this should be ready to merge by today. If not, then ???

### CODE REVIEW

**Comment by mbutrovich** [comment]
So blocked by #484?

**Comment by lmwnshn** [comment]
Yes. But in addition to having those nodes, we need to be able to execute those nodes. Otherwise we will continue to try to bind non-existent things.

**Comment by mbutrovich** [comment]
Should be unblocked now. Will you update the description to reflect the current state and an overview of changes so we can get it reviewed pretty please?

**Comment by yvxiang** [comment]
Does this branch works now?

**Comment by mbutrovich** [comment]
No it's blocked at the moment.

**Comment by mbutrovich** [comment]
Closing since we have a separate branch that this functionality will come from.

**Pull request closed without merging**
