### PR TITLE
Parser Microbenchmark

### PR DESCRIPTION
**Pull request by apavlo**
This is a simple microbenchmark that pumps a bunch of SQL queries through the parser to see how's fast it go. I also added a simple test case to `parser_test` for NOOP queries.

https://www.youtube.com/watch?v=YEfjcJ7Fav0

### CODE REVIEW

**Comment by mbutrovich** [comment]
Do those numbers look reasonable? 64 "complex" statements per second?

**Comment by GustavoAngulo** [comment]
Can we add one more benchmark that are just the TPCC queries? This will help us in the end to end to see if the parser becomes a bottleneck.

**Comment by lmwnshn** [comment]
On release,
```
----------------------------------------------------------------------
Benchmark                               Time           CPU Iterations
----------------------------------------------------------------------
ParserBenchmark/SelectsSimple       12582 ns      12545 ns      55683   311.388k items/s
ParserBenchmark/SelectsComplex   11041966 ns   11003223 ns         63    90.8825 items/s
ParserBenchmark/UpdatesSimple       14043 ns      13958 ns      42923    279.86k items/s
ParserBenchmark/UpdatesComplex     530592 ns     526541 ns       1201   1.85468k items/s
ParserBenchmark/InsertsSimple       13520 ns      13399 ns      50908   291.522k items/s
ParserBenchmark/InsertsComplex    3982390 ns    3982389 ns        145    251.106 items/s
ParserBenchmark/DeletesSimple        8198 ns       8198 ns      80095   476.465k items/s
ParserBenchmark/DeletesComplex   11307470 ns   11307406 ns         63    88.4376 items/s
ParserBenchmark/NOOPs                 510 ns        510 ns    1512440   1.87089M items/s
```

Just libpg_query, (I stripped out the transform to our stuff step),
```
----------------------------------------------------------------------
Benchmark                               Time           CPU Iterations
----------------------------------------------------------------------
ParserBenchmark/SelectsSimple        7391 ns       7391 ns      95860   528.534k items/s
ParserBenchmark/SelectsComplex    4231941 ns    4231994 ns        159    236.295 items/s
ParserBenchmark/UpdatesSimple        8569 ns       8569 ns      63123    455.87k items/s
ParserBenchmark/UpdatesComplex     126951 ns     126950 ns       5224   7.69248k items/s
ParserBenchmark/InsertsSimple        6677 ns       6677 ns      93432   585.039k items/s
ParserBenchmark/InsertsComplex    1931548 ns    1931540 ns        346    517.722 items/s
ParserBenchmark/DeletesSimple        5164 ns       5164 ns     125420   756.492k items/s
ParserBenchmark/DeletesComplex    5139647 ns    5139593 ns        100    194.568 items/s
ParserBenchmark/NOOPs                 342 ns        342 ns    2111073   2.78773M items/s
```

**Comment by mbutrovich** [comment]
> Seems like we add about 2x slowdown to libpg_query.
Makes sense with a transformation pass.

**Comment by apavlo** [comment]
I added @mbutrovich's fixes. If this passes, I will merge.

@GustavoAngulo These queries are pretty simple and are representative of TPC-C. The parser also won't be a bottleneck because we will use prepared statements.

**Pull request merged**
