### PR TITLE
Remove murmur3 from the codebase, bump xxHash version

### PR DESCRIPTION
**Pull request by mbutrovich**
Currently fails some of the HLL tests. Probably need some input from @apavlo since HLL tests are a mystery to me.

### CODE REVIEW

**Comment by apavlo** [comment]
I will look into this tonight / tomorrow

**Comment by mbutrovich** [comment]
This is what the failure looks like on my machine, Jenkins may provide something a bit different.
```
[2019-10-09 17:20:58.936] [optimizer_logger] [trace] Estimated[103] <-> Actual[100]
[2019-10-09 17:20:58.955] [optimizer_logger] [trace] Estimated[10091] <-> Actual[10000]
[2019-10-09 17:20:58.972] [optimizer_logger] [trace] Estimated[955] <-> Actual[1000]
/Users/matt/git/terrier/test/optimizer/hyperloglog_test.cpp:22: Failure
Expected: (estimate) <= (static_cast<double>(actual) * (1 + error)), actual: 113 vs 106.5
Error[0.065000000000000002]: Estimated[113] <-> Actual[100]
[2019-10-09 17:20:59.007] [optimizer_logger] [trace] Estimated[113] <-> Actual[100]
[2019-10-09 17:20:59.025] [optimizer_logger] [trace] Estimated[96493] <-> Actual[100000]
[2019-10-09 17:20:59.077] [optimizer_logger] [trace] Estimated[7428] <-> Actual[10000]
[2019-10-09 17:20:59.077] [optimizer_logger] [trace] Estimated[9949] <-> Actual[10000]
[2019-10-09 17:20:59.078] [optimizer_logger] [trace] Estimated[10068] <-> Actual[10000]
/Users/matt/git/terrier/test/optimizer/hyperloglog_test.cpp:22: Failure
Expected: (estimate) <= (static_cast<double>(actual) * (1 + error)), actual: 10395835 vs 1.0325e+07
Error[0.032500000000000001]: Estimated[10395835] <-> Actual[10000000]
[2019-10-09 17:21:11.370] [optimizer_logger] [trace] Estimated[10395835] <-> Actual[10000000]
```

**Comment by mbutrovich** [comment]
Also the CheckErrorsBounds stuff in the test, instead of EXPECT_LE and EXPECT_GE I think we can use a EXPECT_NEAR as seen in https://github.com/google/googletest/blob/master/googletest/docs/advanced.md

**Comment by mbutrovich** [comment]
This also bumps xxHash to yesterday's release.

**Pull request merged**
