### PR TITLE
Bump xxHash from 0.7.2 to 0.8.0

### PR DESCRIPTION
**Pull request by mbutrovich**
Part of the summer toolchain and third party updates now that TPL2 is in.

Cherry-picking some of the changes from their [releases page](https://github.com/Cyan4973/xxHash/releases):
- api : stabilize XXH3
- perf: automatic vector detection and selection at runtime
- perf: added AVX512 support
- perf: improved speed for large inputs (~+20%)
- perf: improved latency for small inputs (~10%)

LICENSE file was removed since as best as I can tell it's redundant when source code files contain it at the top.

### CODE REVIEW

**Comment by mbutrovich** [comment]
Interestingly, I'm actually seeing a performance regression with a quick benchmark of hashing `VarlenEntry` (which uses xxh3 for non-inlined values). Unclear if we actually want to merge this.

**Comment by mbutrovich** [comment]
I think we want #1055 in first to quantify the performance difference.

**Comment by mbutrovich** [comment]
It certainly seems slower on the machines I test. Maybe we revisit this when/if AVX512 becomes more common? @pmenon thoughts? Do you want to take this branch for a spin on dev5 just to see if it benefits from AVX512?

**Comment by pmenon** [comment]
It's a little faster on `dev5` for strings >= 64 bytes. Unsure if it's worth it, though.

Old version (v0.7.0):
```
VarlenEntryBenchmark/HashInline/1               3 ns          3 ns  209641331     285.7MB/s     285.7M items/s
VarlenEntryBenchmark/HashInline/2               3 ns          3 ns  262292404   714.941MB/s   357.471M items/s
VarlenEntryBenchmark/HashInline/4               3 ns          3 ns  209907888    1.1164GB/s   285.799M items/s
VarlenEntryBenchmark/HashInline/8               3 ns          3 ns  262383548   2.79178GB/s   357.348M items/s
VarlenEntryBenchmark/HashInline/12              3 ns          4 ns  174873490   2.79175GB/s   238.229M items/s
VarlenEntryBenchmark/HashNotInline/16           3 ns          3 ns  262382103   5.58538GB/s   357.464M items/s
VarlenEntryBenchmark/HashNotInline/32           4 ns          4 ns  161412724   6.87111GB/s   219.875M items/s
VarlenEntryBenchmark/HashNotInline/64           7 ns          7 ns   99814794   8.50488GB/s   136.078M items/s
VarlenEntryBenchmark/HashNotInline/128         13 ns         13 ns   53822486   9.16005GB/s   73.2804M items/s
VarlenEntryBenchmark/HashNotInline/256         24 ns         24 ns   28853588   9.82341GB/s   39.2936M items/s
VarlenEntryBenchmark/HashNotInline/512         29 ns         29 ns   24361786    16.461GB/s    32.922M items/s
VarlenEntryBenchmark/HashNotInline/1024        49 ns         49 ns   14309284   19.4676GB/s   19.4676M items/s
VarlenEntryBenchmark/HashNotInline/2048        74 ns         74 ns    9435016    25.686GB/s    12.843M items/s
VarlenEntryBenchmark/HashNotInline/4096       127 ns        127 ns    5502044   29.9646GB/s   7.49115M items/s
```

New version (v.8.0):
```
VarlenEntryBenchmark/HashInline/1               3 ns          3 ns  232638902   317.582MB/s   317.582M items/s
VarlenEntryBenchmark/HashInline/2               3 ns          3 ns  217716058   634.277MB/s   317.138M items/s
VarlenEntryBenchmark/HashInline/4               3 ns          3 ns  232667483   1.24109GB/s   317.718M items/s
VarlenEntryBenchmark/HashInline/8               3 ns          3 ns  262384125   2.79172GB/s    357.34M items/s
VarlenEntryBenchmark/HashInline/12              4 ns          4 ns  190770953    3.0464GB/s    259.96M items/s
VarlenEntryBenchmark/HashNotInline/16           3 ns          3 ns  209904152   4.46473GB/s   285.743M items/s
VarlenEntryBenchmark/HashNotInline/32           4 ns          4 ns  161465588   6.87374GB/s    219.96M items/s
VarlenEntryBenchmark/HashNotInline/64           7 ns          7 ns  104946653   8.93353GB/s   142.937M items/s
VarlenEntryBenchmark/HashNotInline/128         11 ns         11 ns   63551182   10.8299GB/s   86.6389M items/s
VarlenEntryBenchmark/HashNotInline/256         27 ns         27 ns   25697660   8.74037GB/s   34.9615M items/s
VarlenEntryBenchmark/HashNotInline/512         31 ns         31 ns   22267799    15.203GB/s   30.4061M items/s
VarlenEntryBenchmark/HashNotInline/1024        39 ns         39 ns   17983978   24.4892GB/s   24.4892M items/s
VarlenEntryBenchmark/HashNotInline/2048        59 ns         59 ns   11860930   32.3395GB/s   16.1698M items/s
VarlenEntryBenchmark/HashNotInline/4096        59 ns         95 ns    7398176   40.2942GB/s   10.0735M items/s
```

**Comment by mbutrovich** [comment]
We can punt on this for now, then.

**Pull request closed without merging**
