### PR TITLE
Document and enforce the alignment assumption in RawConcurrentBitmap.

### PR DESCRIPTION
**Pull request by lmwnshn**
Added to class header and to the function that assumes this.

### CODE REVIEW

**Comment by mbutrovich** [comment]
Why doesn't Allocate() enforce this requirement? I realize we currently only using it in testing, but it seems odd not to enforce alignment requirement in its own internal Allocate() function.

**Comment by tli2** [comment]
Actually, better still, TERRIER_ASSERT this requirement (`this % 8 == 0`) where the correctness of code depends on this

**Comment by lmwnshn** [comment]
@mbutrovich 

Will we ever use Allocate outside of testing? I added an assert there, but technically the Allocate function itself should ensure it returns some 64-bit aligned memory. Though I'm not sure how that works right now.

**Comment by tli2** [comment]
@lmwnshn You can use `AllocationUtil`

**Pull request merged**
