### PR TITLE
clang-tidy heartbeat

### PR DESCRIPTION
**Pull request by lmwnshn**
clang-tidy can be so slow that Travis kills us while waiting for our progress bar to update.
This just prints stuff to stdout every 300 seconds (half Travis timeout) so that we don't get killed.

### CODE REVIEW

**Comment by jrolli** [comment]
This CI failure for this PR is fixed by #372.

**Comment by codeworm96** [comment]
We are still experiencing this problem in our PR(#341).
The problems are:
1. This heartbeat message is not forced to be flushed immediately. So it may retain in the buffer.
2. `update_progress()` function does not print a update for each invocation. It is possible that we are continuously putting some files into the task_queue at such a speed that 1) it does not trigger the timeout and 2) makes `update_progress()` function not print a update for a period longer than Travis timeout.

Currently, we are mitigating this problem with https://github.com/cmu-db/terrier/pull/341/commits/94154c1d78b3bde76a03c865d0fff39dcd5dbadb.

**Comment by mbutrovich** [comment]
@codeworm96 Assuming your changes resolve the issue, can you please cherry pick those changes to a separate PR?

**Comment by codeworm96** [comment]
@mbutrovich Sure.

**Pull request merged**
