### PR TITLE
Extended Query protocol testing

### PR DESCRIPTION
**Pull request by bialesdaniel**
I added extended query mode to:
- unit tests
- terrier pipeline E2E performance test
- nightly performance tests

### CODE REVIEW

**Comment by bialesdaniel** [comment]
@crd477 We were talking with Andy today and we were wondering if you could do something with the permissions to allow one member of our team to make changes to the Jenkinsfile. We just want to be able to test that it works correctly before merging the PR

**Comment by crd477** [comment]
Sorry I missed this the other day.

> @crd477 We were talking with Andy today and we were wondering if you could do something with the permissions to allow one member of our team to make changes to the Jenkinsfile. We just want to be able to test that it works correctly before merging the PR

The authorization is based on GitHub privileges, and I don't see any controls within Jenkins to override this for specific individuals.

This honestly feels more to me like a process issue than a technical one.  I think a better model would be to work entirely within your own fork, create a pipeline for that in our Jenkins (where you naturally have the necessary permissions to make changes to Jenkinsfiles), and make changes and test them there.  Once you're happy with the status and have a passing build, only then submit a PR to upstream.  This is what I've done for myself when I wanted to propose structural changes to the terrier pipeline.  I can point to a branch within my fork and say, "hey, if this looks OK, I'll submit a PR".  You can see an example of what I mean here:
http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/crd%2Fterrier-937-test/detail/issue-937/3/pipeline
(Sorry I can't point to a better example right now because I've already deleted the branches that would've been most useful.)

I also put my personal things in a separate folder in Jenkins just to keep the main view less cluttered.

The other solution would be for Andy to give you, Daniel, write permissions on the terrier repo.  Although this is the easiest solution, some problems in the past were the unexpected consequences of changes by project members with more privileges in the main repo.

**Comment by bialesdaniel** [comment]
> Sorry I missed this the other day.
> 
> > @crd477 We were talking with Andy today and we were wondering if you could do something with the permissions to allow one member of our team to make changes to the Jenkinsfile. We just want to be able to test that it works correctly before merging the PR
> 
> The authorization is based on GitHub privileges, and I don't see any controls within Jenkins to override this for specific individuals.
> 
> This honestly feels more to me like a process issue than a technical one. I think a better model would be to work entirely within your own fork, create a pipeline for that in our Jenkins (where you naturally have the necessary permissions to make changes to Jenkinsfiles), and make changes and test them there. Once you're happy with the status and have a passing build, only then submit a PR to upstream. This is what I've done for myself when I wanted to propose structural changes to the terrier pipeline. I can point to a branch within my fork and say, "hey, if this looks OK, I'll submit a PR". You can see an example of what I mean here:
> http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/crd%2Fterrier-937-test/detail/issue-937/3/pipeline
> (Sorry I can't point to a better example right now because I've already deleted the branches that would've been most useful.)
> 
> I also put my personal things in a separate folder in Jenkins just to keep the main view less cluttered.
> 
> The other solution would be for Andy to give you, Daniel, write permissions on the terrier repo. Although this is the easiest solution, some problems in the past were the unexpected consequences of changes by project members with more privileges in the main repo.

That sounds like a great solution. I'll work on setting that up. I'll post a link to this PR when I have it working.

**Comment by bialesdaniel** [comment]
Here is an example of the pipeline passing (I had to run the E2E Debugging cause it had a random failure). I'm not sure if I got unlucky or if extended query protocol increases the random errors cause I had to restart the pipeline twice. http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier/detail/performance-tests-extended-protocol/8/pipeline/149

**Comment by bialesdaniel** [comment]
Oh also this one which didn't pass but Yao has a PR to fix the issue here http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/testing-team%2Fterrier-nightly/detail/performance-tests-extended-protocol/2/pipeline

**Pull request merged**
