### PR TITLE
Create OLTP-Bench Test Script

### PR DESCRIPTION
**Pull request by benliangw**
This PR is related to issue #817.

- Extract startup/shutdown utility code.
- Create an OLTP-Bench test script.
- Switch run_junit.py from python2 to python3

### CODE REVIEW

**Comment by skyfishjy** [comment]
@crd477 
Could you please help us check this PR? We updated [Jenkinsfile](https://github.com/cmu-db/terrier/pull/840/files#diff-58231b16fdee45a03a4ee3cf94a9f2c3) but Jenkins is [not](http://jenkins.db.cs.cmu.edu:8080/blue/organizations/jenkins/terrier/detail/PR-840/3/pipeline) using the updated one.

Also, we plan to migrate python 2 to 3. Are there any extra infrastructure codes we should add before the migration? Please let us know. Thanks.

**Comment by crd477** [comment]
This is the result of the trust policy enforced by the GitHub Branch Source plugin in Jenkins.  It is currently configured to allow modified Jenkinsfiles only in pull requests from users with Admin or Write permission in the origin branch.  You can read more about this policy in, "[Behavior options for GitHub branch sources](https://docs.cloudbees.com/docs/admin-resources/latest/pipelines-user-guide/pipeline-as-code#_behavior_options_for_github_branch_sources)".
There are at least 3 solutions, in increasing order of trust delegation:
1. I can manually replay your changes directly in Jenkins just for this PR
1. someone with admin or write privileges in the project can open a new PR from the same  `cmu-mse-cmudb/terrier-issue-817:master` branch
1. someone with admin privileges in the project can grant you write privileges

I can do either of the first two but I'd like to hear from @apavlo or @mbutrovich about how they want to proceed.

**Comment by crd477** [comment]
> Also, we plan to migrate python 2 to 3. Are there any extra infrastructure codes we should add before the migration? Please let us know. Thanks

No.  As long as anything you depend on is accounted for in the installation process, then there should not be any required changes in the underlying infrastructure.  In other words, if your changes work from scratch in an unmodified Docker container or VM, then it should be fine in the CI environment too.

**Comment by skyfishjy** [comment]
> > Also, we plan to migrate python 2 to 3. Are there any extra infrastructure codes we should add before the migration? Please let us know. Thanks
> 
> No. As long as anything you depend on is accounted for in the installation process, then there should not be any required changes in the underlying infrastructure. In other words, if your changes work from scratch in an unmodified Docker container or VM, then it should be fine in the CI environment too.

Thanks for the information

**Comment by apavlo** [comment]
i will create a new PR

**Pull request closed without merging**
