### PR TITLE
Fix self joins which use index joins

### PR DESCRIPTION
**Pull request by abalakumar083**
This is a bug fix for https://github.com/cmu-db/terrier/issues/998.

The issue with self-joins occurs when deriving the index bounds for an index join. Specifically, the problem is we only use table oid to determine which column value expression is a bound for the input table. Since in a self join there are two tables with the same table oid, in some cases we end up choosing a bound which references the wrong table. 

Later in the optimizer since the parent trims the input column set based on the table aliases the child provides - the parent discards the input columns to which the incorrect bound refers to. So it's not possible to convert the column value expressions to derived value expressions which causes the observed errors. 

Anyways the fix is simple, in order to make sure the bounds refer to the correct table, we check that the column value expression chosen as the bound has both the same table oid and also the same table name as the input table.

### CODE REVIEW

**Comment by mbutrovich** [comment]
Naive question: why is the fix in the optimizer related to table names at all? Shouldn't everything have been resolved to oids by now?

**Comment by abalakumar083** [comment]
> Naive question: why is the fix in the optimizer related to table names at all? Shouldn't everything have been resolved to oids by now?

**Comment by abalakumar083** [comment]
So, I think you can use table oids to do all the things you currently use table aliases for inside of optimizer groups. That's probably the better way to fix this - i'll try and see if that works.

**Comment by apavlo** [comment]
@dniu16 Add the queries listed here *after* we merge this PR: https://github.com/cmu-db/terrier/issues/998

**Pull request merged**
